// This file is automatically generated by the Open Roberta Lab.
#define _ARDUINO_STL_NOT_NEEDED
#include "SenseBoxMCU.h"
#undef max
#undef min
#include <NEPODefs.h>






void setup()
{
    Serial.begin(9600);
    
}

void loop()
{
    Serial.println("Hallo");
}