// This file is automatically generated by the Open Roberta Lab.
#define _ARDUINO_STL_NOT_NEEDED
#include "SenseBoxMCU.h"
#undef max
#undef min
#include <NEPODefs.h>
#include <stdlib.h>



void sensors();


double ___numVar;
bool ___boolVar;
String ___stringVar;
unsigned int ___colourVar;
std::list<double> ___numList;
std::list<bool> ___boolList;
std::list<String> ___stringList;
std::list<unsigned int> ___colourList;
int _input_S3 = 2;
int _mic_S4 = 1;
SDS011 _sds011_S5(Serial1);

BMX055 _bmx055_B;
int _getValueFromBmx(int axis, int mode) {
    int _x_axis;
    int _y_axis;
    int _z_axis;
    switch (mode) {
        case 1:
            _bmx055_B.getRotation(&_x_axis, &_y_axis, &_z_axis);
            break;
        case 2:
            _bmx055_B.getMagnet(&_x_axis, &_y_axis, &_z_axis);
            break;
    }
    switch (axis) {
        case 1:
            return _x_axis;
        case 2:
            return _y_axis;
        case 3:
            return _z_axis;
    }
}

HDC1080 _hdc1080_H;
GPS _gps_G2;
int _output_L = 5;
int _potentiometer_P = 3;
int _button_B3 = 6;
BMP280 _bmp280_T;
VEML6070 _veml_V;
TSL45315 _tsl_V;
int _input_S2 = 4;
unsigned long __time_1 = millis();


void sensors() {
    Serial.println(analogRead(_input_S3));
    Serial.println(digitalRead(_input_S2));
    Serial.println(digitalRead(_button_B3));
    Serial.println(analogRead(_output_L)/10.24);
    Serial.println(((double)analogRead(_potentiometer_P))*5/1024);
    Serial.println(get_microphone_volume(_mic_S4));
    Serial.println(_hdc1080_H.getHumidity());
    Serial.println(_hdc1080_H.getTemperature());
    Serial.println(_bmp280_T.getTemperature());
    Serial.println(_bmp280_T.getPressure());
    Serial.println(_tsl_V.getIlluminance());
    Serial.println(_veml_V.getUvIntensity());
    Serial.println(_bmx055_B.getAccelerationX());
    Serial.println(_bmx055_B.getAccelerationY());
    Serial.println(_bmx055_B.getAccelerationZ());
    Serial.println(_sds011_S5.getPm25());
    Serial.println(_sds011_S5.getPm10());
    Serial.println(_gps_G2.getLatitude());
    Serial.println(_gps_G2.getLongitude());
    Serial.println(_gps_G2.getAltitude());
    Serial.println(_gps_G2.getSpeed());
    Serial.println(_gps_G2.getDate());
    Serial.println(_gps_G2.getTime());
    Serial.println((int) (millis() - __time_1));
    __time_1 = millis();
}

void setup()
{
    Serial.begin(9600);
    
    pinMode(_input_S3, INPUT);
    Serial1.begin(9600);
    _bmx055_B.beginAcc(0x03);
    _hdc1080_H.begin();
    _gps_G2.begin();
    pinMode(_button_B3, INPUT);
    _bmp280_T.begin();
    _veml_V.begin();
    _tsl_V.begin();
    pinMode(_input_S2, INPUT);
    ___numVar = 0;
    ___boolVar = true;
    ___stringVar = "";
    ___colourVar = RGB(0xFF, 0xFF, 0xFF);
    ___numList = {0, 0, 0};
    ___boolList = {true, true, true};
    ___stringList = {"", "", ""};
    ___colourList = {RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF), RGB(0xFF, 0xFF, 0xFF)};
}

void loop()
{
    sensors();
}